const dashboardData = {
  updatedAt: "2026-05-28 17:42:16",
  stats: [
    { label: "风险总数", value: "68", unit: "件", trend: "+5", tone: "danger" },
    { label: "中风险", value: "17", unit: "件", trend: "+3", tone: "warning" },
    { label: "高风险", value: "13", unit: "件", trend: "+1", tone: "danger" },
    { label: "重大风险", value: "3", unit: "件", trend: "+1", tone: "danger" },
  ],
  riskLevels: [
    { level: "低风险", count: 35, color: "#38bdf8" },
    { level: "中风险", count: 17, color: "#facc15" },
    { level: "高风险", count: 13, color: "#fb923c" },
    { level: "重大风险", count: 3, color: "#f43f5e" },
  ],
  typeRatios: [
    { name: "第三方施工", count: 18, color: "#fb5a70" },
    { name: "应力应变", count: 14, color: "#fb923c" },
    { name: "阴极保护", count: 11, color: "#facc15" },
    { name: "泄漏检测", count: 8, color: "#8b7cf6" },
    { name: "压力检测", count: 17, color: "#22d3ee" },
  ],
  stationRiskRatios: [
    {
      station: "凉风垭储配站",
      total: 12,
      segments: [
        { name: "第三方施工", value: 24, color: "#fb5a70" },
        { name: "应力应变", value: 18, color: "#fb923c" },
        { name: "阴极保护", value: 14, color: "#facc15" },
        { name: "泄漏检测", value: 9, color: "#8b7cf6" },
        { name: "压力检测", value: 35, color: "#22d3ee" },
      ],
    },
    {
      station: "垫江工业园区配气站",
      total: 15,
      segments: [
        { name: "第三方施工", value: 32, color: "#fb5a70" },
        { name: "应力应变", value: 19, color: "#fb923c" },
        { name: "阴极保护", value: 11, color: "#facc15" },
        { name: "泄漏检测", value: 13, color: "#8b7cf6" },
        { name: "压力检测", value: 25, color: "#22d3ee" },
      ],
    },
    {
      station: "澄溪工业园区配气站",
      total: 10,
      segments: [
        { name: "第三方施工", value: 22, color: "#fb5a70" },
        { name: "应力应变", value: 16, color: "#fb923c" },
        { name: "阴极保护", value: 20, color: "#facc15" },
        { name: "泄漏检测", value: 12, color: "#8b7cf6" },
        { name: "压力检测", value: 30, color: "#22d3ee" },
      ],
    },
    {
      station: "澄溪强生调压站",
      total: 9,
      segments: [
        { name: "第三方施工", value: 14, color: "#fb5a70" },
        { name: "应力应变", value: 21, color: "#fb923c" },
        { name: "阴极保护", value: 18, color: "#facc15" },
        { name: "泄漏检测", value: 10, color: "#8b7cf6" },
        { name: "压力检测", value: 37, color: "#22d3ee" },
      ],
    },
    {
      station: "（五）沙坪配气站",
      total: 8,
      segments: [
        { name: "第三方施工", value: 18, color: "#fb5a70" },
        { name: "应力应变", value: 14, color: "#fb923c" },
        { name: "阴极保护", value: 24, color: "#facc15" },
        { name: "泄漏检测", value: 16, color: "#8b7cf6" },
        { name: "压力检测", value: 28, color: "#22d3ee" },
      ],
    },
    {
      station: "高安配气站",
      total: 14,
      segments: [
        { name: "第三方施工", value: 20, color: "#fb5a70" },
        { name: "应力应变", value: 12, color: "#fb923c" },
        { name: "阴极保护", value: 13, color: "#facc15" },
        { name: "泄漏检测", value: 9, color: "#8b7cf6" },
        { name: "压力检测", value: 46, color: "#22d3ee" },
      ],
    },
  ],
  risks: [
    {
      id: "construction",
      name: "第三方施工",
      shortName: "施工",
      icon: "TC",
      score: 76,
      activeAlerts: 6,
      location: "工业园支线 K03+180 周边施工区",
      formula: "设备风险×0.25 + 行为风险×0.25 + 距离风险×0.30 + 时间风险×0.10 + 环境风险×0.10",
      factors: [
        { name: "设备风险", value: 90, weight: 0.25 },
        { name: "行为风险", value: 70, weight: 0.25 },
        { name: "距离风险", value: 100, weight: 0.3 },
        { name: "时间风险", value: 60, weight: 0.1 },
        { name: "环境风险", value: 40, weight: 0.1 },
      ],
      metrics: [
        { label: "施工设备", value: "打桩机", state: "高危设备" },
        { label: "距管道中心线", value: "8 m", state: "红区" },
        { label: "持续时间", value: "24 min", state: "持续靠近" },
      ],
      analysis: {
        cause: "视频识别到打桩机在管道红线范围内持续作业，GIS显示与管道中心线距离不足10米。",
        impact: "可能造成防腐层破坏、管道局部变形、泄漏风险增加；重大情况下可能引发火灾、爆炸和区域停气。",
        advice: "立即推送GIS坐标，联动周边视频追踪，派工现场核查施工许可证并要求暂停施工，必要时通知110、119和应急抢修队。",
      },
      trend: [28, 31, 35, 40, 52, 58, 64, 70, 74, 77, 80, 76],
    },
    {
      id: "strain",
      name: "应力应变",
      shortName: "应变",
      icon: "SS",
      score: 68,
      activeAlerts: 3,
      location: "桂溪-长龙输配干线 K08+900",
      formula: "应力异常×0.35 + 应变变化×0.25 + 温度补偿×0.15 + 设备状态×0.15 + 历史风险×0.10",
      factors: [
        { name: "应力异常", value: 72, weight: 0.35 },
        { name: "应变变化", value: 68, weight: 0.25 },
        { name: "温度补偿", value: 44, weight: 0.15 },
        { name: "设备状态", value: 60, weight: 0.15 },
        { name: "历史风险", value: 50, weight: 0.1 },
      ],
      metrics: [
        { label: "环向应变", value: "412 με", state: "持续抬升" },
        { label: "温度补偿", value: "31.2℃", state: "已修正" },
        { label: "变化趋势", value: "+6.8%", state: "高位波动" },
      ],
      analysis: {
        cause: "管段应变数据持续高于同类点位基线，可能与地基沉降、外部荷载或管道局部受力集中有关。",
        impact: "可能造成管道疲劳累积、焊缝受力增加，长期发展会提高泄漏和结构损伤风险。",
        advice: "建议联动历史沉降、施工和巡检记录，安排现场复测并对异常点位加密监测。",
      },
      trend: [36, 39, 44, 48, 52, 55, 59, 63, 66, 69, 71, 68],
    },
    {
      id: "cathodic",
      name: "阴极保护",
      shortName: "阴保",
      icon: "CP",
      score: 54,
      activeAlerts: 4,
      location: "澄溪片区阴保测试桩 CP-017",
      formula: "保护电位异常×0.40 + 电流输出异常×0.20 + 通断电变化×0.15 + 设备状态×0.15 + 历史风险×0.10",
      factors: [
        { name: "保护电位", value: 58, weight: 0.4 },
        { name: "电流输出", value: 52, weight: 0.2 },
        { name: "通断电变化", value: 46, weight: 0.15 },
        { name: "设备状态", value: 48, weight: 0.15 },
        { name: "历史风险", value: 50, weight: 0.1 },
      ],
      metrics: [
        { label: "保护电位", value: "-0.78 V", state: "低于建议值" },
        { label: "输出电流", value: "1.9 A", state: "偏低" },
        { label: "测试桩状态", value: "在线", state: "需复核" },
      ],
      analysis: {
        cause: "阴极保护电位偏低，可能存在阳极地床老化、接线松动或杂散电流干扰。",
        impact: "可能导致管道防腐保护不足，提升局部腐蚀和后续泄漏风险。",
        advice: "建议巡检阴保测试桩和恒电位仪状态，复测保护电位并排查杂散电流影响。",
      },
      trend: [30, 33, 35, 39, 42, 46, 50, 53, 56, 55, 54, 54],
    },
    {
      id: "leak",
      name: "泄漏检测",
      shortName: "泄漏",
      icon: "LD",
      score: 82,
      activeAlerts: 5,
      location: "桂阳街道阀井 V-032",
      formula: "可燃气浓度×0.40 + 压力流量平衡×0.25 + 声光/视频异常×0.15 + 扩散环境×0.10 + 历史风险×0.10",
      factors: [
        { name: "可燃气浓度", value: 90, weight: 0.4 },
        { name: "压力流量平衡", value: 76, weight: 0.25 },
        { name: "声光/视频异常", value: 70, weight: 0.15 },
        { name: "扩散环境", value: 60, weight: 0.1 },
        { name: "历史风险", value: 50, weight: 0.1 },
      ],
      metrics: [
        { label: "可燃气浓度", value: "18%LEL", state: "持续升高" },
        { label: "阀井状态", value: "异常", state: "需处置" },
        { label: "周边环境", value: "居民区", state: "敏感区域" },
      ],
      analysis: {
        cause: "阀井周边可燃气浓度持续升高，并伴随压力流量平衡异常，存在疑似泄漏迹象。",
        impact: "可能造成燃气积聚、火灾爆炸和人员伤害风险，居民区场景下社会影响较大。",
        advice: "建议立即升级最高级告警，联动现场检测、阀门控制和人员疏散，并通知抢险队伍处置。",
      },
      trend: [45, 48, 52, 56, 60, 66, 72, 78, 83, 85, 84, 82],
    },
    {
      id: "pressure",
      name: "压力检测",
      shortName: "压力",
      icon: "PD",
      score: 64,
      activeAlerts: 5,
      location: "桂溪-长龙输配干线 K12+400",
      formula: "压力异常风险×0.35 + 流量异常风险×0.25 + 设备状态风险×0.20 + 压力变化趋势风险×0.15 + 历史风险×0.05",
      factors: [
        { name: "压力异常", value: 72, weight: 0.35 },
        { name: "流量异常", value: 60, weight: 0.25 },
        { name: "设备状态", value: 56, weight: 0.2 },
        { name: "变化趋势", value: 70, weight: 0.15 },
        { name: "历史风险", value: 35, weight: 0.05 },
      ],
      metrics: [
        { label: "运行压力", value: "1.56 MPa", state: "超上限" },
        { label: "入口/出口流量差", value: "18.2%", state: "偏高" },
        { label: "5分钟压力变化", value: "+8.7%", state: "快速上升" },
      ],
      analysis: {
        cause: "压力监测终端显示局部管段压力偏高，可能与下游阀门开度、调压设备状态或瞬时用气波动有关。",
        impact: "可能造成局部超压、供气波动和设备负载增加，持续发展会带来泄漏或停输风险。",
        advice: "建议调度中心持续关注高压列表，优先核查压力大于1.50MPa的站点并联动现场巡检。",
      },
      trend: [42, 45, 47, 48, 52, 55, 60, 64, 69, 73, 68, 64],
    },
  ],
  controlAreas: [
    { riskId: "construction", name: "第三方施工", area: "工业园支线 K03+180 周边施工区", focus: "施工红线、机械作业、许可证核验" },
    { riskId: "strain", name: "应力应变", area: "桂溪-长龙输配干线 K08+900", focus: "沉降点、焊缝段、外部荷载影响区" },
    { riskId: "cathodic", name: "阴极保护", area: "澄溪片区阴保测试桩 CP-017", focus: "测试桩、恒电位仪、杂散电流干扰区" },
    { riskId: "leak", name: "泄漏检测", area: "桂阳街道阀井 V-032", focus: "阀井、居民区、可燃气扩散范围" },
    { riskId: "pressure", name: "压力检测", area: "桂溪-长龙输配干线 K12+400", focus: "高压站点、调压设备、末端波动区域" },
  ],
  pressureTypes: [
    { name: "低风险", count: 35, active: true },
    { name: "中风险", count: 17 },
    { name: "高风险", count: 13 },
    { name: "重大风险", count: 3 },
  ],
  constructionVideos: [
    {
      title: "工业园支线 K03+180 打桩机靠近",
      time: "2026-05-30 17:42:16",
      camera: "工业园北侧 03#球机",
      distance: "8m红区",
      level: "重大风险",
      beforeAfter: "前后30s视频",
      frequency: { low: 0, medium: 1, high: 3, critical: 2 },
      cause: "视频识别到打桩机在管道红线范围内持续作业，距离管道中心线不足10米。",
      impact: "可能造成防腐层破坏、管道局部变形、泄漏风险增加，严重时可能引发火灾爆炸。",
      advice: "立即调阅前后30秒视频，派工现场核实施工许可并要求暂停施工。",
      thumbnail: "linear-gradient(135deg, rgba(251, 90, 112, .82), rgba(7, 17, 31, .2)), repeating-linear-gradient(115deg, #10233b 0 18px, #0a1729 18px 36px)",
    },
    {
      title: "长龙配气站外工程车停留",
      time: "2026-05-30 17:39:08",
      camera: "长龙站外 01#枪机",
      distance: "28m管控区",
      level: "高风险",
      beforeAfter: "前后30s视频",
      frequency: { low: 1, medium: 2, high: 2, critical: 0 },
      cause: "工程车在管道管控区内停留时间超过阈值，存在靠近施工风险。",
      impact: "可能影响管道周边土体稳定，增加第三方破坏隐患。",
      advice: "调阅前后30秒视频确认作业行为，通知属地网格现场劝离并登记施工主体。",
      thumbnail: "linear-gradient(135deg, rgba(251, 146, 60, .82), rgba(7, 17, 31, .2)), repeating-linear-gradient(45deg, #0f2845 0 16px, #0b1a2e 16px 32px)",
    },
    {
      title: "澄溪末端施工围挡新增",
      time: "2026-05-30 17:35:44",
      camera: "澄溪末端 02#枪机",
      distance: "46m关注区",
      level: "中风险",
      beforeAfter: "前后30s视频",
      frequency: { low: 2, medium: 2, high: 0, critical: 0 },
      cause: "视频识别到新增施工围挡，当前距离处于关注区间。",
      impact: "若后续出现机械进场，可能升级为施工靠近风险。",
      advice: "保留视频证据，持续跟踪该点位并提醒巡检人员关注施工进展。",
      thumbnail: "linear-gradient(135deg, rgba(250, 204, 21, .76), rgba(7, 17, 31, .2)), repeating-linear-gradient(90deg, #12253d 0 20px, #0b1a2e 20px 40px)",
    },
    {
      title: "桂阳阀井旁小型挖机进场",
      time: "2026-05-30 17:31:26",
      camera: "桂阳阀井 04#球机",
      distance: "16m管控区",
      level: "高风险",
      beforeAfter: "前后30s视频",
      frequency: { low: 1, medium: 1, high: 3, critical: 0 },
      cause: "小型挖机进入管道管控区并短暂停留，存在后续开挖作业可能。",
      impact: "可能造成管道周边覆土扰动，叠加阀井区域设备密集，需防止风险升级。",
      advice: "点击回看前后30秒视频确认机械轨迹，通知巡检人员到场核实作业计划。",
      thumbnail: "linear-gradient(135deg, rgba(56, 189, 248, .74), rgba(7, 17, 31, .24)), repeating-linear-gradient(135deg, #12395a 0 14px, #0b1a2e 14px 28px)",
    },
    {
      title: "高安门站外吊车临停",
      time: "2026-05-30 17:28:53",
      camera: "高安门站 02#枪机",
      distance: "35m关注区",
      level: "中风险",
      beforeAfter: "前后30s视频",
      frequency: { low: 2, medium: 3, high: 1, critical: 0 },
      cause: "吊车在门站外关注区临时停靠，尚未识别到吊装动作。",
      impact: "若后续发生吊装或支腿压覆，可能影响管道周边地面荷载。",
      advice: "保留前后30秒视频证据，持续跟踪车辆是否离场或开展吊装。",
      thumbnail: "linear-gradient(135deg, rgba(139, 124, 246, .78), rgba(7, 17, 31, .24)), repeating-linear-gradient(60deg, #18294e 0 15px, #0c1729 15px 30px)",
    },
    {
      title: "长龙支线施工人员聚集",
      time: "2026-05-30 17:24:11",
      camera: "长龙支线 05#枪机",
      distance: "62m低风险区",
      level: "低风险",
      beforeAfter: "前后30s视频",
      frequency: { low: 4, medium: 1, high: 0, critical: 0 },
      cause: "识别到施工人员在低风险区聚集，暂未发现机械作业或开挖动作。",
      impact: "当前影响较低，但可能发展为施工进场前置行为。",
      advice: "持续抽帧观察，若出现机械设备或围挡变化则自动升级预警。",
      thumbnail: "linear-gradient(135deg, rgba(52, 211, 153, .7), rgba(7, 17, 31, .24)), repeating-linear-gradient(100deg, #123d3a 0 18px, #0b1a2e 18px 36px)",
    },
  ],
  strainRows: [
    {
      time: "2026-05-30 17:42:16",
      station: "桂溪-长龙 K08+900",
      region: "重庆/垫江/鼎发燃气",
      code: "DF-SS-0007",
      type: "管道应力应变监测终端",
      strain: "412",
      level: "高风险",
      frequency: { low: 2, medium: 3, high: 4, critical: 0 },
      cause: "该点位环向应变连续高于基线区间，变化速率较近7日均值抬升。",
      impact: "可能存在外部荷载、地基沉降或局部受力集中，持续发展会增加焊缝疲劳风险。",
      advice: "联动巡检记录与周边施工信息，安排现场复测并加密采样频次。",
    },
    {
      time: "2026-05-30 17:41:48",
      station: "凉风垭储配站外环线",
      region: "重庆/垫江/鼎发燃气",
      code: "DF-SS-0012",
      type: "管道应力应变监测终端",
      strain: "386",
      level: "高风险",
      frequency: { low: 3, medium: 3, high: 3, critical: 0 },
      cause: "站外环线应变值持续上浮，温度补偿后仍处于高位。",
      impact: "可能造成局部管段长期受力偏高，影响管道结构稳定性。",
      advice: "建议核查管道覆土、道路荷载与支墩状态，必要时现场开挖复测。",
    },
    {
      time: "2026-05-30 17:41:20",
      station: "垫江工业园区配气站",
      region: "重庆/垫江/鼎发燃气",
      code: "DF-SS-0021",
      type: "管道应力应变监测终端",
      strain: "344",
      level: "中风险",
      frequency: { low: 4, medium: 4, high: 1, critical: 0 },
      cause: "园区支线应变出现阶段性波动，疑似周边车辆荷载变化影响。",
      impact: "短时影响有限，但连续波动可能诱发管段疲劳累积。",
      advice: "保持趋势观察，联动视频确认周边车辆和施工通行情况。",
    },
    {
      time: "2026-05-30 17:40:51",
      station: "澄溪工业园区配气站",
      region: "重庆/垫江/鼎发燃气",
      code: "DF-SS-0028",
      type: "管道应力应变监测终端",
      strain: "318",
      level: "中风险",
      frequency: { low: 5, medium: 3, high: 1, critical: 0 },
      cause: "监测点应变值接近关注阈值，变化趋势呈缓慢上升。",
      impact: "可能反映管沟周边土体状态变化，需防止趋势性累积。",
      advice: "纳入重点点位观察，若连续三次上升则派发现场巡检。",
    },
    {
      time: "2026-05-30 17:40:22",
      station: "澄溪强生调压站",
      region: "重庆/垫江/鼎发燃气",
      code: "DF-SS-0033",
      type: "管道应力应变监测终端",
      strain: "276",
      level: "低风险",
      frequency: { low: 6, medium: 2, high: 0, critical: 0 },
      cause: "应变值轻微波动，当前仍在可控范围内。",
      impact: "暂未形成明显结构风险，需持续与温度补偿数据比对。",
      advice: "维持自动监测，下一采样周期继续观察变化率。",
    },
    {
      time: "2026-05-30 17:39:54",
      station: "高安配气站外输配线",
      region: "重庆/垫江/鼎发燃气",
      code: "DF-SS-0040",
      type: "管道应力应变监测终端",
      strain: "251",
      level: "正常",
      frequency: { low: 7, medium: 1, high: 0, critical: 0 },
      cause: "监测值处于正常波动区间，未发现持续抬升迹象。",
      impact: "当前不影响管道结构安全。",
      advice: "保持常规监测，作为同类点位基线参考。",
    },
  ],
  cathodicRows: [
    { time: "2026-05-30 17:42:16", station: "澄溪CP-017", offPotential: "-0.66", sustainedHours: 2, dcDensity: "18.4", acDensity: "4.2", acVoltage: "7.8", naturalPotential: "-0.78", anodeOpenPotential: "1.21", anodeCurrent: "42", signal: "92%", battery: "3.61", level: "重大风险", frequency: { low: 2, medium: 3, high: 3, critical: 1 }, cause: "断电电位连续2小时高于-0.68V，交流干扰和输出电流波动同时出现。", impact: "可能导致该区段阴极保护不足，提升局部腐蚀和后续泄漏风险。", advice: "安排复测断电电位，排查测试桩接线、恒电位仪输出和杂散电流干扰。" },
    { time: "2026-05-30 17:41:46", station: "桂溪CP-009", offPotential: "-0.74", sustainedHours: 2, dcDensity: "15.7", acDensity: "3.5", acVoltage: "6.9", naturalPotential: "-0.82", anodeOpenPotential: "1.18", anodeCurrent: "38", signal: "88%", battery: "3.58", level: "高风险", frequency: { low: 4, medium: 3, high: 2, critical: 0 }, cause: "断电电位连续2小时处于-0.77V至-0.68V区间，阳极输出电流较上周期偏低。", impact: "可能造成保护裕度不足，长期会提高腐蚀风险。", advice: "持续观察两轮采样，必要时校准恒电位仪输出参数。" },
    { time: "2026-05-30 17:41:16", station: "高安CP-023", offPotential: "-0.88", sustainedHours: 2, dcDensity: "11.2", acDensity: "2.6", acVoltage: "5.1", naturalPotential: "-0.91", anodeOpenPotential: "1.09", anodeCurrent: "31", signal: "84%", battery: "3.54", level: "正常", frequency: { low: 5, medium: 2, high: 0, critical: 0 }, cause: "断电电位处于-1.20V至-0.85V正常保护区间，信号强度下降但仍保持在线。", impact: "当前影响有限，需防止通信质量影响后续数据连续性。", advice: "纳入设备巡检清单，关注信号强度和电池电压变化。" },
    { time: "2026-05-30 17:40:46", station: "长龙CP-014", offPotential: "-0.95", sustainedHours: 2, dcDensity: "9.8", acDensity: "2.1", acVoltage: "4.6", naturalPotential: "-0.95", anodeOpenPotential: "1.04", anodeCurrent: "29", signal: "81%", battery: "3.49", level: "正常", frequency: { low: 6, medium: 1, high: 0, critical: 0 }, cause: "断电电位处于正常区间，设备信号略有衰减。", impact: "当前不形成明显腐蚀风险。", advice: "维持常规监测，低电量阈值触发前安排设备维护。" },
    { time: "2026-05-30 17:40:16", station: "沙坪CP-031", offPotential: "-0.83", sustainedHours: 2, dcDensity: "13.6", acDensity: "3.1", acVoltage: "6.2", naturalPotential: "-0.84", anodeOpenPotential: "1.15", anodeCurrent: "35", signal: "86%", battery: "3.56", level: "低风险", frequency: { low: 4, medium: 1, high: 0, critical: 0 }, cause: "断电电位连续2小时处于-0.85V至-0.81V区间，疑似周边用电设施产生交流干扰。", impact: "可能削弱局部管段防腐保护效果。", advice: "建议排查附近电力设施和接地系统，复核交流干扰源。" },
    { time: "2026-05-30 17:39:46", station: "工业园CP-026", offPotential: "-0.79", sustainedHours: 2, dcDensity: "16.9", acDensity: "4.6", acVoltage: "8.4", naturalPotential: "-0.76", anodeOpenPotential: "1.23", anodeCurrent: "44", signal: "90%", battery: "3.62", level: "中风险", frequency: { low: 2, medium: 3, high: 1, critical: 0 }, cause: "断电电位连续2小时处于-0.81V至-0.77V区间，交流电压和交流电流密度同步升高。", impact: "可能加速交流腐蚀，影响工业园区支线完整性。", advice: "优先派工复测交流干扰，必要时调整排流保护措施。" },
  ],
  pressureRiskRows: [
    {
      time: "2026-05-30 17:42:16",
      station: "桂溪站",
      region: "重庆/垫江/鼎发燃气",
      code: "DF-PT-0001",
      type: "智能远程压力监测终端",
      pressure: "1.56",
      level: "重大风险",
      frequency: { low: 2, medium: 4, high: 5, critical: 2 },
      cause: "近30分钟压力持续高于站点标准区间，疑似下游阀门开度不足或调压器输出偏高。",
      impact: "可能造成局部超压、阀门密封受损和管段应力增加，持续发展会提升泄漏风险。",
      advice: "优先派工核查桂溪站出口阀门和调压器参数，联动调度中心降低输出压力并持续观察10分钟趋势。",
    },
    {
      time: "2026-05-30 17:41:58",
      station: "长龙配气站",
      region: "重庆/垫江/鼎发燃气",
      code: "DF-PT-0014",
      type: "智能远程压力监测终端",
      pressure: "1.51",
      level: "高风险",
      frequency: { low: 3, medium: 3, high: 4, critical: 1 },
      cause: "入口压力偏高且出口流量变化较小，可能与上游供气波动和站内调压响应滞后有关。",
      impact: "可能引发下游管段压力不均衡，影响末端用户稳定供气。",
      advice: "通知站点值守人员复核调压器状态，调取近1小时压力曲线并关注是否继续上升。",
    },
    {
      time: "2026-05-30 17:41:43",
      station: "工业园调压箱",
      region: "重庆/垫江/鼎发燃气",
      code: "DF-PT-0027",
      type: "智能远程压力监测终端",
      pressure: "1.49",
      level: "高风险",
      frequency: { low: 5, medium: 4, high: 3, critical: 0 },
      cause: "工业园用气负荷短时下降，调压箱出口压力回落不及时。",
      impact: "可能造成园区支线压力波动，局部设备负载增加。",
      advice: "建议持续监测并提醒园区用户侧调度，必要时调整调压箱设定值。",
    },
    {
      time: "2026-05-30 17:41:20",
      station: "澄溪末端监测点",
      region: "重庆/垫江/鼎发燃气",
      code: "DF-PT-0035",
      type: "智能远程压力监测终端",
      pressure: "1.43",
      level: "中风险",
      frequency: { low: 6, medium: 3, high: 1, critical: 0 },
      cause: "末端压力处于关注区间，可能受上游调压和居民用气峰值切换影响。",
      impact: "短时影响较小，但连续波动可能影响末端供气稳定性。",
      advice: "保留观察，若连续三次采样升高则转派巡检复核。",
    },
    {
      time: "2026-05-30 17:40:55",
      station: "桂阳街道阀井",
      region: "重庆/垫江/鼎发燃气",
      code: "DF-PT-0042",
      type: "智能远程压力监测终端",
      pressure: "1.39",
      level: "低风险",
      frequency: { low: 7, medium: 2, high: 1, critical: 0 },
      cause: "阀井压力略高于日常均值，当前未出现快速上升特征。",
      impact: "暂无明显影响，需防止与阀门状态异常叠加。",
      advice: "纳入自动巡检清单，下一轮采样继续比对阀门开度和压力趋势。",
    },
    {
      time: "2026-05-30 17:40:31",
      station: "高安门站",
      region: "重庆/垫江/鼎发燃气",
      code: "DF-PT-0058",
      type: "智能远程压力监测终端",
      pressure: "1.36",
      level: "正常",
      frequency: { low: 8, medium: 2, high: 0, critical: 0 },
      cause: "压力处于轻微波动区间，可能为正常用气波动。",
      impact: "风险较低，当前不影响供气连续性。",
      advice: "维持自动监测，不触发人工工单。",
    },
  ],
  leakRows: [
    {
      time: "2026-05-30 17:42:16",
      station: "桂阳街道阀井 V-032",
      region: "重庆/垫江/鼎发燃气",
      code: "DF-GAS-0032",
      type: "物联网阀门井气体报警器",
      pressure: "0.42MPa",
      gas: "18%LEL",
      level: "重大风险",
      frequency: { low: 1, medium: 2, high: 4, critical: 3 },
      cause: "阀井内可燃气浓度持续升高，疑似井室密闭空间内存在燃气积聚。",
      impact: "可能造成井室燃气聚集、火灾爆炸和周边居民区安全风险。",
      advice: "立即派抢险人员现场检测，联动阀门控制和周边警戒，必要时开展人员疏散。",
    },
    {
      time: "2026-05-30 17:39:22",
      station: "澄溪末端阀井 V-018",
      region: "重庆/垫江/鼎发燃气",
      code: "DF-GAS-0018",
      type: "物联网阀门井气体报警器",
      pressure: "0.39MPa",
      gas: "9%LEL",
      level: "高风险",
      frequency: { low: 3, medium: 3, high: 2, critical: 0 },
      cause: "阀井气体报警器出现连续两次高位读数，可能受井盖密闭和微量泄漏叠加影响。",
      impact: "可能形成局部可燃气聚集，影响巡检人员进入作业安全。",
      advice: "安排现场复测并保持通风，复核阀井周边接口和法兰密封状态。",
    },
    {
      time: "2026-05-30 17:37:58",
      station: "工业园区阀井 V-041",
      region: "重庆/垫江/鼎发燃气",
      code: "DF-GAS-0041",
      type: "物联网阀门井气体报警器",
      pressure: "0.36MPa",
      gas: "6%LEL",
      level: "中风险",
      frequency: { low: 4, medium: 3, high: 1, critical: 0 },
      cause: "阀井内气体浓度短时上升，可能与井室通风不畅或微量泄漏有关。",
      impact: "若浓度继续升高，可能影响巡检进入作业并触发周边安全管控。",
      advice: "建议先远程复核连续采样值，派巡检人员现场通风并复测接口密封。",
    },
    {
      time: "2026-05-30 17:36:44",
      station: "凉风垭储配站阀室 V-009",
      region: "重庆/垫江/鼎发燃气",
      code: "DF-GAS-0009",
      type: "物联网阀门井气体报警器",
      pressure: "0.34MPa",
      gas: "4%LEL",
      level: "低风险",
      frequency: { low: 6, medium: 1, high: 0, critical: 0 },
      cause: "低浓度波动，疑似环境背景值或短时通风变化导致。",
      impact: "当前风险较低，但仍需防止异常值持续累积。",
      advice: "维持自动监测，若连续三次上升则转人工复核。",
    },
    {
      time: "2026-05-30 17:35:26",
      station: "沙坪配气站阀井 V-052",
      region: "重庆/垫江/鼎发燃气",
      code: "DF-GAS-0052",
      type: "物联网阀门井气体报警器",
      pressure: "0.41MPa",
      gas: "11%LEL",
      level: "高风险",
      frequency: { low: 2, medium: 3, high: 3, critical: 0 },
      cause: "阀井气体读数升至高风险区间，且与上游压力波动时间接近。",
      impact: "可能存在接口微漏或井室积聚，需防止浓度进入爆炸下限危险区。",
      advice: "立即派工复测并保持井室通风，联动压力数据判断是否需要临时降压。",
    },
    {
      time: "2026-05-30 17:34:12",
      station: "高安配气站阀井 V-063",
      region: "重庆/垫江/鼎发燃气",
      code: "DF-GAS-0063",
      type: "物联网阀门井气体报警器",
      pressure: "0.33MPa",
      gas: "3%LEL",
      level: "正常",
      frequency: { low: 5, medium: 1, high: 0, critical: 0 },
      cause: "读数处于正常波动范围，设备在线状态稳定。",
      impact: "当前不影响现场安全作业。",
      advice: "保持常规采样，作为同类阀井背景值参考。",
    },
  ],
  events: [
    { riskId: "pressure", level: "重大", title: "桂溪-长龙干线压力持续升高", time: "17:32", owner: "调度中心", status: "现场核查" },
    { riskId: "construction", level: "重大", title: "打桩机进入管道10米红区", time: "17:28", owner: "巡检二组", status: "已派工" },
    { riskId: "strain", level: "高", title: "K08+900应变数据持续抬升", time: "17:19", owner: "输配企业", status: "趋势研判" },
    { riskId: "leak", level: "高", title: "桂阳街道阀井疑似泄漏", time: "17:05", owner: "抢险队", status: "现场检测" },
    { riskId: "construction", level: "中", title: "工程车长时间停留管道周边", time: "16:48", owner: "属地网格", status: "视频跟踪" },
  ],
  assistantPrompts: [
    "当前最高风险是什么？",
    "生成高压风险处置建议",
    "第三方施工风险怎么闭环？",
    "脱硫厂违规事件如何描述？",
  ],
  agents: [
    { name: "脱硫厂人员作业安全监测", tag: "视频AI", initials: "脱" },
    { name: "天然气保供智能调度", tag: "保供研判", initials: "保" },
    { name: "码上服务", tag: "企业诉求", initials: "码" },
    { name: "安燃易问", tag: "安全问答", initials: "问" },
    { name: "经济运行成效评估", tag: "产业评估", initials: "评" },
  ],
  flow: ["数据采集", "异常检测", "风险评分", "告警生成", "工单派发", "处置复核", "闭环归档"],
};
